### ISSUE TITLE
Lack of data for 2023

### ISSUE THREAD

**Issue by kifgep** [SleepyBag/moyu#1]
Dear Developer,

The application met error due to lack of holiday data for 2023, please help or suggest!

**Comment by SleepyBag** [comment]
应该是由于上游 `chinese_calendar` 库没有更新数据造成的。现在应该没有问题了

**Comment by SleepyBag** [comment]
@kifgep `chinese_calendar` 要通过更新库版本来更新数据，所以需要你在机器上运行 `pip install -U chinese_calendar` 更新一下
